### ISSUE TITLE
Not an issue at all, just an invitation

### ISSUE THREAD

**Issue by richardba** [cc-icons/cc-icons#1]
Hello there, this is an invitation for usage, it seems that all you guys requested Creative Commons icons and banners at Font Awesome, so I'm going to deliver them all as a yet another css library, easy to use.

http://cc-icons.github.io/installation/

@jeffreycrow, @thisliquidspace, @JorgenSmith, @oluc, @TheSeg. @russkel, @simonpai, @acrobotic, @grantneufeld, @davidhdz, @hamishcampbell, @fnagel, @websirnik, @tasmo, @dezza, @idleberg, @jgsnell, @xero, @alanguir, @awesomerobot, @Jylhis, @Tonkonozhenko, @cr3473, @tagliala, @hobbsy, @rriemann, @melanie, @maurozadu, @fubarhouse, @emaV, @jorge-d, @abbottjam, @marvinrabe, @DominikWro, @VA6DAH, @oraculus, @Gexos, @perre, @gaplauche, @AndrewKvalheim, @gaplauche, @sixlettervariables, @designisokay, @netotaku, @fubarhouse, @thotzl, @gemmaweirs, @slashsBin

**Comment by tasmo** [comment]
Thank you! I like it more to host it at the same server where the website is stored. But good service idea anyways.

**Comment by marvinrabe** [comment]
Great :-) … Thank you!
