### ISSUE TITLE
cdn links missing https

### ISSUE THREAD

**Issue by walchko** [cc-icons/cc-icons#5]
Great work, I really like these! 👍 

The example links on [cc-icons.github.io/installation](http://cc-icons.github.io/installation/) are missing `https` before the `//` in the `href`:

```html
<link href="//cdnjs.cloudflare.com/ajax/libs/cc-icons/1.2.1/css/cc-icons.min.css" rel="stylesheet">
```

They should be:

```html
<link href="https://cdnjs.cloudflare.com/ajax/libs/cc-icons/1.2.1/css/cc-icons.min.css" rel="stylesheet">
```

**Comment by richardba** [comment]
Hi @walchko !!! Thanks for your submission, however there is a reason why there is no protocol before the // [as stated in here](https://www.paulirish.com/2010/the-protocol-relative-url/), using https in resources has a terrible drawback issue, and omitting it has a performance benefits

Regards
